# This file defines both environments and includes the active-env file.
# This file NEVER changes during a blue/green switch.

upstream kk-api-blue {
    server 127.0.0.1:4000;
    keepalive 32;
}

upstream kk-api-green {
    server 127.0.0.1:3000;
    keepalive 32;
}

server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/kijanikiosk.access.log;
    error_log  /var/log/nginx/kijanikiosk.error.log;

    # The active environment is declared in this include file.
    # Switch environments by replacing this file and reloading nginx.
    include /etc/nginx/kijanikiosk-active-env.conf;
}

