pipeline {
    agent any
    environment {
        NODE_ENV = "test"
        BUILD_DIR = "dist"
        APP_NAME = "apis-and-fetch"
    }
    options{
        timeout(time: 15, unit: "MINUTES")
        buildDiscarder(logRotator(numToKeepStr: "10"))
        disableConcurrentBuilds()
    }
    stages {
        stage("Build"){
            steps {
                echo "Installing dependencies for ${APP_NAME}..."
                sh "npm ci"
            }
        }
        stage("Test"){
            steps {
                echo "Test stage: TODO"
            }
        }
        stage("Archive"){
            steps {
                echo "Archive stage: TODO"
            }
        }
    }
    post {
        success {
            echo "Pipeline succeded. ${APP_NAME} build ${BUILD_NUMBER}"
        }
        failure {
            echo "Pipeline FAILED: ${APP_NAME} build ${BUILD_NUMBER} - check logs"
        }
        always {
            echo "Build URL: ${BUILD_URL}"
        }
    }
}