[api]
api-staging ansible_host=13.245.158.95

[payments]
payments-staging ansible_host=13.245.236.137

[logs]
logs-staging ansible_host=13.247.77.253

[kijanikiosk:children]
api
payments
logs

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
